# Generated by Django 5.0.14 on 2026-05-30 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre identificativo de la estación o sensor IoT.', max_length=100, unique=True)),
                ('location_geom', models.TextField(help_text='Coordenadas geográficas de la estación (Geometry: Point, SRID 4326).')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la estación está operativa y enviando reportes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación Meteorológica',
                'verbose_name_plural': 'Estaciones Meteorológicas',
                'db_table': 'gis_weather_stations',
            },
        ),
        migrations.CreateModel(
            name='SensorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de la lectura telemétrica.')),
                ('temperature', models.FloatField(help_text='Temperatura registrada en grados Celsius (°C).')),
                ('humidity', models.FloatField(help_text='Humedad relativa porcentual (%) registrada (0.0 - 100.0).')),
                ('wind_speed', models.FloatField(help_text='Velocidad del viento registrada en kilómetros por hora (km/h).')),
                ('wind_direction', models.FloatField(blank=True, help_text='Dirección del viento en grados azimut (0 - 360).', null=True)),
                ('station', models.ForeignKey(help_text='Estación meteorológica de origen.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='project_gis.weatherstation')),
            ],
            options={
                'verbose_name': 'Métrica de Sensor',
                'verbose_name_plural': 'Métricas de Sensores',
                'db_table': 'gis_sensor_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
