# Generated by Django 5.0.14 on 2026-05-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFireRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(help_text='Coordenadas del foco de origen del incendio (Geometry: Point, SRID 4326).')),
                ('burned_area', models.TextField(blank=True, help_text='Polígono del perímetro total devastado por el fuego (Geometry: Polygon, SRID 4326).', null=True)),
                ('ndvi_average', models.FloatField(help_text='Índice de Vegetación de Diferencia Normalizada promedio (Salud forestal antes del fuego).')),
                ('nbr_average', models.FloatField(help_text='Índice de Calcinación Normalizada promedio (Severidad del área quemada).')),
                ('max_temperature', models.FloatField(help_text='Temperatura máxima registrada durante el inicio del incendio (°C).')),
                ('min_humidity', models.FloatField(help_text='Humedad relativa mínima registrada durante el inicio del incendio (%).')),
                ('max_wind_speed', models.FloatField(help_text='Velocidad máxima del viento registrada (km/h).')),
                ('fire_date', models.DateTimeField(help_text='Fecha y hora aproximada en que se detectó el incendio forestal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Histórico de Incendio',
                'verbose_name_plural': 'Registros Históricos de Incendios',
                'db_table': 'ia_historical_fire_records',
                'ordering': ['-fire_date'],
            },
        ),
    ]
