# Generated by Django 5.0.14 on 2026-05-30 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción y reportes de campo sobre la evolución del incidente.')),
                ('severity', models.CharField(choices=[('BAJA', 'Severidad Baja'), ('MEDIA', 'Severidad Media'), ('ALTA', 'Severidad Alta'), ('EXTREMA', 'Severidad Extrema')], db_index=True, default='BAJA', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo / En Combate'), ('CONTROLADO', 'Bajo Control'), ('EXTINGUIDO', 'Extinguido')], db_index=True, default='ACTIVO', max_length=15)),
                ('location', models.TextField(help_text='Centro geográfico del incidente (Geometry: Point, SRID 4326).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, help_text='Usuario que ingresó la alerta en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente Activo',
                'verbose_name_plural': 'Incidentes Activos',
                'db_table': 'incidents_active_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvacuationPerimeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perimeter', models.TextField(help_text='Polígono georreferenciado de evacuación y riesgo extremo (Geometry: Polygon, SRID 4326).')),
                ('area_hectares', models.FloatField(help_text='Área de evacuación calculada en hectáreas.')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el perímetro de evacuación sigue vigente y vigilado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(help_text='Incidente vinculado.', on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_perimeters', to='incidents.activeincident')),
            ],
            options={
                'verbose_name': 'Perímetro de Evacuación',
                'verbose_name_plural': 'Perímetros de Evacuación',
                'db_table': 'incidents_evacuation_perimeters',
            },
        ),
    ]
